app: rudixlab

service: twitter
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  timeout: 10
functions:
  app:
    handler: server.handler
    memorySize: 512
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
